CREATE TABLE IF NOT EXISTS label (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

ALTER TABLE "user"
ADD COLUMN label_id BIGINT NULL DEFAULT NULL
ON CONFLICT DO NOTHING;

ALTER TABLE "user"
ADD CONSTRAINT fk_user_label
FOREIGN KEY (label_id) REFERENCES label (id)
ON DELETE SET NULL
ON UPDATE CASCADE
ON CONFLICT DO NOTHING;

ALTER TABLE album
ADD COLUMN label_id BIGINT NULL
ON CONFLICT DO NOTHING;

ALTER TABLE album
ADD CONSTRAINT fk_album_label
FOREIGN KEY (label_id) REFERENCES label (id)
ON DELETE SET NULL
ON UPDATE CASCADE
ON CONFLICT DO NOTHING;

ALTER TABLE artist
ADD COLUMN label_id BIGINT NULL
ON CONFLICT DO NOTHING;

ALTER TABLE artist
ADD CONSTRAINT fk_artist_label
FOREIGN KEY (label_id) REFERENCES label (id)
ON DELETE SET NULL
ON UPDATE CASCADE
ON CONFLICT DO NOTHING;

---- create above / drop below ----

ALTER TABLE album DROP CONSTRAINT IF EXISTS fk_album_label;
ALTER TABLE album DROP COLUMN IF EXISTS label_id;

ALTER TABLE artist DROP CONSTRAINT IF EXISTS fk_artist_label;
ALTER TABLE artist DROP COLUMN IF EXISTS label_id;

ALTER TABLE "user" DROP CONSTRAINT IF EXISTS fk_user_label;
ALTER TABLE "user" DROP COLUMN IF EXISTS label_id;

DROP TABLE IF EXISTS label;