version: "2"

run:
  concurrency: 8
  timeout: 20m
  issues-exit-code: 1
  tests: false

linters:
  enable:
    - errcheck
    - goconst
    - govet
    - ineffassign
    - staticcheck
    - unused
    
  settings:
    govet:
      enable-all: false
      enable:
        - shadow
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 3

formatters:
  enable:
    - goimports
    - gofmt
  settings:
    goimports:
      local-prefixes:
        - github.com/go-park-mail-ru/2025_1_Return_Zero
    gofmt:
      simplify: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
