// Code generated by MockGen. DO NOT EDIT.
// Source: domain/usecase.go
//
// Generated by this command:
//
//	mockgen -source=domain/usecase.go -destination=mocks/mock_usecase.go
//

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	context "context"
	reflect "reflect"

	usecase "github.com/go-park-mail-ru/2025_1_Return_Zero/microservices/playlist/model/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
	isgomock struct{}
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// AddTrackToPlaylist mocks base method.
func (m *MockUsecase) AddTrackToPlaylist(ctx context.Context, request *usecase.AddTrackToPlaylistRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTrackToPlaylist", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTrackToPlaylist indicates an expected call of AddTrackToPlaylist.
func (mr *MockUsecaseMockRecorder) AddTrackToPlaylist(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTrackToPlaylist", reflect.TypeOf((*MockUsecase)(nil).AddTrackToPlaylist), ctx, request)
}

// CreatePlaylist mocks base method.
func (m *MockUsecase) CreatePlaylist(ctx context.Context, playlist *usecase.CreatePlaylistRequest) (*usecase.Playlist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePlaylist", ctx, playlist)
	ret0, _ := ret[0].(*usecase.Playlist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePlaylist indicates an expected call of CreatePlaylist.
func (mr *MockUsecaseMockRecorder) CreatePlaylist(ctx, playlist any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePlaylist", reflect.TypeOf((*MockUsecase)(nil).CreatePlaylist), ctx, playlist)
}

// GetCombinedPlaylistsByUserID mocks base method.
func (m *MockUsecase) GetCombinedPlaylistsByUserID(ctx context.Context, request *usecase.GetCombinedPlaylistsByUserIDRequest) (*usecase.PlaylistList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCombinedPlaylistsByUserID", ctx, request)
	ret0, _ := ret[0].(*usecase.PlaylistList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCombinedPlaylistsByUserID indicates an expected call of GetCombinedPlaylistsByUserID.
func (mr *MockUsecaseMockRecorder) GetCombinedPlaylistsByUserID(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCombinedPlaylistsByUserID", reflect.TypeOf((*MockUsecase)(nil).GetCombinedPlaylistsByUserID), ctx, request)
}

// GetPlaylistByID mocks base method.
func (m *MockUsecase) GetPlaylistByID(ctx context.Context, request *usecase.GetPlaylistByIDRequest) (*usecase.PlaylistWithIsLiked, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaylistByID", ctx, request)
	ret0, _ := ret[0].(*usecase.PlaylistWithIsLiked)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaylistByID indicates an expected call of GetPlaylistByID.
func (mr *MockUsecaseMockRecorder) GetPlaylistByID(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaylistByID", reflect.TypeOf((*MockUsecase)(nil).GetPlaylistByID), ctx, request)
}

// GetPlaylistTrackIds mocks base method.
func (m *MockUsecase) GetPlaylistTrackIds(ctx context.Context, request *usecase.GetPlaylistTrackIdsRequest) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaylistTrackIds", ctx, request)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaylistTrackIds indicates an expected call of GetPlaylistTrackIds.
func (mr *MockUsecaseMockRecorder) GetPlaylistTrackIds(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaylistTrackIds", reflect.TypeOf((*MockUsecase)(nil).GetPlaylistTrackIds), ctx, request)
}

// GetPlaylistsToAdd mocks base method.
func (m *MockUsecase) GetPlaylistsToAdd(ctx context.Context, request *usecase.GetPlaylistsToAddRequest) (*usecase.GetPlaylistsToAddResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaylistsToAdd", ctx, request)
	ret0, _ := ret[0].(*usecase.GetPlaylistsToAddResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaylistsToAdd indicates an expected call of GetPlaylistsToAdd.
func (mr *MockUsecaseMockRecorder) GetPlaylistsToAdd(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaylistsToAdd", reflect.TypeOf((*MockUsecase)(nil).GetPlaylistsToAdd), ctx, request)
}

// GetProfilePlaylists mocks base method.
func (m *MockUsecase) GetProfilePlaylists(ctx context.Context, request *usecase.GetProfilePlaylistsRequest) (*usecase.GetProfilePlaylistsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfilePlaylists", ctx, request)
	ret0, _ := ret[0].(*usecase.GetProfilePlaylistsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfilePlaylists indicates an expected call of GetProfilePlaylists.
func (mr *MockUsecaseMockRecorder) GetProfilePlaylists(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfilePlaylists", reflect.TypeOf((*MockUsecase)(nil).GetProfilePlaylists), ctx, request)
}

// LikePlaylist mocks base method.
func (m *MockUsecase) LikePlaylist(ctx context.Context, request *usecase.LikePlaylistRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LikePlaylist", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// LikePlaylist indicates an expected call of LikePlaylist.
func (mr *MockUsecaseMockRecorder) LikePlaylist(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LikePlaylist", reflect.TypeOf((*MockUsecase)(nil).LikePlaylist), ctx, request)
}

// RemovePlaylist mocks base method.
func (m *MockUsecase) RemovePlaylist(ctx context.Context, request *usecase.RemovePlaylistRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemovePlaylist", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemovePlaylist indicates an expected call of RemovePlaylist.
func (mr *MockUsecaseMockRecorder) RemovePlaylist(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovePlaylist", reflect.TypeOf((*MockUsecase)(nil).RemovePlaylist), ctx, request)
}

// RemoveTrackFromPlaylist mocks base method.
func (m *MockUsecase) RemoveTrackFromPlaylist(ctx context.Context, request *usecase.RemoveTrackFromPlaylistRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTrackFromPlaylist", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveTrackFromPlaylist indicates an expected call of RemoveTrackFromPlaylist.
func (mr *MockUsecaseMockRecorder) RemoveTrackFromPlaylist(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTrackFromPlaylist", reflect.TypeOf((*MockUsecase)(nil).RemoveTrackFromPlaylist), ctx, request)
}

// SearchPlaylists mocks base method.
func (m *MockUsecase) SearchPlaylists(ctx context.Context, request *usecase.SearchPlaylistsRequest) (*usecase.PlaylistList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchPlaylists", ctx, request)
	ret0, _ := ret[0].(*usecase.PlaylistList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchPlaylists indicates an expected call of SearchPlaylists.
func (mr *MockUsecaseMockRecorder) SearchPlaylists(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchPlaylists", reflect.TypeOf((*MockUsecase)(nil).SearchPlaylists), ctx, request)
}

// UpdatePlaylist mocks base method.
func (m *MockUsecase) UpdatePlaylist(ctx context.Context, request *usecase.UpdatePlaylistRequest) (*usecase.Playlist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlaylist", ctx, request)
	ret0, _ := ret[0].(*usecase.Playlist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePlaylist indicates an expected call of UpdatePlaylist.
func (mr *MockUsecaseMockRecorder) UpdatePlaylist(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlaylist", reflect.TypeOf((*MockUsecase)(nil).UpdatePlaylist), ctx, request)
}

// UpdatePlaylistsPublisityByUserID mocks base method.
func (m *MockUsecase) UpdatePlaylistsPublisityByUserID(ctx context.Context, request *usecase.UpdatePlaylistsPublisityByUserIDRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlaylistsPublisityByUserID", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePlaylistsPublisityByUserID indicates an expected call of UpdatePlaylistsPublisityByUserID.
func (mr *MockUsecaseMockRecorder) UpdatePlaylistsPublisityByUserID(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlaylistsPublisityByUserID", reflect.TypeOf((*MockUsecase)(nil).UpdatePlaylistsPublisityByUserID), ctx, request)
}

// UploadPlaylistThumbnail mocks base method.
func (m *MockUsecase) UploadPlaylistThumbnail(ctx context.Context, playlist *usecase.UploadPlaylistThumbnailRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadPlaylistThumbnail", ctx, playlist)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadPlaylistThumbnail indicates an expected call of UploadPlaylistThumbnail.
func (mr *MockUsecaseMockRecorder) UploadPlaylistThumbnail(ctx, playlist any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadPlaylistThumbnail", reflect.TypeOf((*MockUsecase)(nil).UploadPlaylistThumbnail), ctx, playlist)
}
