{
 "title": "API dashboard",
 "tags": [ "Golang" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "AuthHandlers",
    "query": {
     "query": "label_values(api_http_requests_total,path)"
    }
   },
   {
    "name": "UserHandlers",
    "query": {
     "query": "label_values(api_http_requests_total,path)"
    }
   },
   {
    "name": "ArtistsHandlers",
    "query": {
     "query": "label_values(api_http_requests_total,path)"
    }
   },
   {
    "name": "AlbumsHandlers",
    "query": {
     "query": "label_values(api_http_requests_total,path)"
    }
   },
   {
    "name": "TracksHandlers",
    "query": {
     "query": "label_values(api_http_requests_total,path)"
    }
   },
   {
    "name": "PlaylistsHandlers",
    "query": {
     "query": "label_values(api_http_requests_total,path)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Go Runtime Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "All Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "go_goroutines{job!~\"prometheus|node-exporter\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Api Goroutines",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 11, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "go_goroutines{job=\"api\"}",
       "legendFormat": "Api Goroutines"
      }
     ]
    },
    {
     "title": "Heap in Kbytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 655 },
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{job!~\"prometheus|node-exporter\"} / (1024)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Api Heap in Kbytes",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 11, "y": 655 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{job=\"api\"} / (1024)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "API Handlers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 5, "y": 663 },
     "targets": [
      { "expr": "api_http_requests_total", "legendFormat": "{{path}}" }
     ]
    }
   ]
  },
  {
   "title": "Auth handler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS AuthHandlers",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum without(status)(\n  rate(\n    api_http_requests_total{\n      path=~\"$AuthHandlers\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "$AuthHandlers"
      }
     ]
    },
    {
     "title": "AuthHandlers - timings",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 240 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by (le, path) (rate(api_http_request_duration_seconds_bucket{path=~\"$AuthHandlers\"}[$__rate_interval])))",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "ART AuthHandlers",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 250 },
     "targets": [
      {
       "expr": "(rate(api_http_request_duration_seconds_sum{path=~\"$AuthHandlers\"}[$__rate_interval]) / rate(api_http_request_duration_seconds_count{path=~\"$AuthHandlers\"}[$__rate_interval])) * 1000",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "RPS Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 260 },
     "targets": [
      {
       "expr": "rate(api_http_requests_total{path=~\"$AuthHandlers\", status!=\"200\"}[$__rate_interval])",
       "legendFormat": "{{path}}, {{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "User handler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS UserHandlers",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum without(status)(\n  rate(\n    api_http_requests_total{\n      path=~\"$UserHandlers\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{path}}, {{method}}"
      }
     ]
    },
    {
     "title": "UserHandlers - timings",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by (le, path, method) (rate(api_http_request_duration_seconds_bucket{path=~\"$UserHandlers\"}[$__rate_interval])))",
       "legendFormat": "{{path}}, {{method}}"
      }
     ]
    },
    {
     "title": "ART UserHandlers",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "(rate(api_http_request_duration_seconds_sum{path=~\"$UserHandlers\"}[$__rate_interval]) / rate(api_http_request_duration_seconds_count{path=~\"$UserHandlers\"}[$__rate_interval])) * 1000",
       "legendFormat": "{{path}}, {{method}}"
      }
     ]
    },
    {
     "title": "RPS Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "rate(api_http_requests_total{path=~\"$UserHandlers\", status!=\"200\"}[$__rate_interval])",
       "legendFormat": "{{path}}, {{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Artists handler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS ArtistsHandlers ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "sum without(status)(\n  rate(\n    api_http_requests_total{\n      path=~\"$ArtistsHandlers\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{path}}, {{method}}"
      }
     ]
    },
    {
     "title": "ArtistsHandlers - timings",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by (le, path, method) (rate(api_http_request_duration_seconds_bucket{path=~\"$ArtistsHandlers\"}[$__rate_interval])))",
       "legendFormat": "{{path}}, {{method}}"
      }
     ]
    },
    {
     "title": "ART ArtistsHandlers",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 62 },
     "targets": [
      {
       "expr": "(rate(api_http_request_duration_seconds_sum{path=~\"$ArtistsHandlers\"}[$__rate_interval]) / rate(api_http_request_duration_seconds_count{path=~\"$ArtistsHandlers\"}[$__rate_interval])) * 1000",
       "legendFormat": "{{path}}, {{method}}"
      }
     ]
    },
    {
     "title": "RPS Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
     "targets": [
      {
       "expr": "rate(api_http_requests_total{path=~\"$ArtistsHandlers\", status!=\"200\"}[$__rate_interval])",
       "legendFormat": "{{path}}, {{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Albums handler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS $AlbumsHandlers ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 81 },
     "targets": [
      {
       "expr": "sum without(status)(\n  rate(\n    api_http_requests_total{\n      path=~\"$AlbumsHandlers\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{path}}, {{method}}"
      }
     ]
    },
    {
     "title": "AlbumsHandlers - timings",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 91 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by (le, path, method) (rate(api_http_request_duration_seconds_bucket{path=~\"$AlbumsHandlers\"}[$__rate_interval])))",
       "legendFormat": "{{path}}, {{method}}"
      }
     ]
    },
    {
     "title": "ART AlbumsHandlers",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 101 },
     "targets": [
      {
       "expr": "(rate(api_http_request_duration_seconds_sum{path=~\"$AlbumsHandlers\"}[$__rate_interval]) / rate(api_http_request_duration_seconds_count{path=~\"$AlbumsHandlers\"}[$__rate_interval]))",
       "legendFormat": "{{path}}, {{method}}"
      }
     ]
    },
    {
     "title": "RPS Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
     "targets": [
      {
       "expr": "rate(api_http_requests_total{path=~\"$AlbumsHandlers\", status!=\"200\"}[$__rate_interval])",
       "legendFormat": "{{path}}, {{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tracks handler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS $TracksHandlers ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 82 },
     "targets": [
      {
       "expr": "sum without(status)(\n  rate(\n    api_http_requests_total{\n      path=~\"$TracksHandlers\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{path}}, {{method}}"
      }
     ]
    },
    {
     "title": "$TracksHandlers - timings",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 92 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by (le, path, method) (rate(api_http_request_duration_seconds_bucket{path=~\"$TracksHandlers\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ART $TracksHandlers",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 102 },
     "targets": [
      {
       "expr": "(rate(api_http_request_duration_seconds_sum{path=~\"$TracksHandlers\"}[$__rate_interval]) / rate(api_http_request_duration_seconds_count{path=~\"$TracksHandlers\"}[$__rate_interval])) * 1000",
       "legendFormat": "{{path}}, {{method}}"
      }
     ]
    },
    {
     "title": "RPS Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
     "targets": [
      {
       "expr": "rate(api_http_requests_total{path=~\"$TracksHandlers\", status!=\"200\"}[$__rate_interval])",
       "legendFormat": "{{path}}, {{status}}"
      }
     ]
    }
   ]
  }
 ]
}