{
 "title": "Track service",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "GRPCHandlers",
    "query": {
     "query": "label_values(track_service_grpc_number_of_requests_total,method)"
    }
   },
   {
    "name": "DBHandlers",
    "query": {
     "query": "label_values(track_service_database_duration_seconds_bucket,operation)"
    }
   }
  ]
 },
 "panels": [
  { "title": "GRPC Handler ($GRPCHandlers)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "GRPCHandlers" },
  {
   "title": "$GRPCHandlers RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(track_service_grpc_number_of_requests_total{method=\"/track.TrackService/${GRPCHandlers}\"}[$__rate_interval])\n",
     "legendFormat": "$GRPCHandlers"
    }
   ]
  },
  {
   "title": "$GRPCHandlers  timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le, method) (rate(track_service_grpc_request_duration_seconds_bucket{method=~\"/track.TrackService/$GRPCHandlers\"}[$__rate_interval])))",
     "legendFormat": "{{method}}, {{le}}"
    }
   ]
  },
  { "title": "DB Handler ($DBHandlers)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "DBHandlers" },
  {
   "title": "Timing $DBHandlers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le, operation) (rate(track_service_database_duration_seconds_bucket{operation=~\"$DBHandlers\"}[$__rate_interval])))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "$DBHandlers Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(track_service_database_errors_total{operation=\"$DBHandlers\"}[$__rate_interval])",
     "legendFormat": "{{operation}}"
    }
   ]
  }
 ]
}