basePath: /
definitions:
  delivery.APIBadRequestErrorResponse:
    description: API bad request error response structure
    properties:
      error:
        example: Something went wrong
        type: string
      status:
        example: 400
        type: integer
    type: object
  delivery.APIInternalServerErrorResponse:
    description: API internal server error response structure
    properties:
      error:
        example: Something went wrong
        type: string
      status:
        example: 500
        type: integer
    type: object
  delivery.APIResponse:
    description: API response wrapper
    properties:
      body: {}
      status:
        example: 200
        type: integer
    type: object
  delivery.Album:
    description: A music album entity
    properties:
      artist:
        type: string
      artist_id:
        example: 1
        type: integer
      id:
        example: 1
        type: integer
      release_date:
        example: "2021-01-01"
        type: string
      thumbnail_url:
        example: https://example.com/album.jpg
        type: string
      title:
        example: Anticyclone
        type: string
      type:
        allOf:
        - $ref: '#/definitions/delivery.AlbumType'
        example: album
    type: object
  delivery.AlbumType:
    enum:
    - album
    - ep
    - compilation
    - single
    type: string
    x-enum-varnames:
    - AlbumTypeAlbum
    - AlbumTypeEP
    - AlbumTypeCompilation
    - AlbumTypeSingle
  delivery.Artist:
    description: A music artist entity
    properties:
      description:
        example: Inabakumori is a Japanese artist
        type: string
      id:
        example: 1
        type: integer
      thumbnail_url:
        example: https://example.com/artist.jpg
        type: string
      title:
        example: Inabakumori
        type: string
    type: object
  delivery.ArtistDetailed:
    description: A detailed music artist entity
    properties:
      description:
        example: Inabakumori is a Japanese artist
        type: string
      favorites_count:
        example: 1000
        type: integer
      id:
        example: 1
        type: integer
      listeners_count:
        example: 1000
        type: integer
      thumbnail_url:
        example: https://example.com/artist.jpg
        type: string
      title:
        example: Inabakumori
        type: string
    type: object
  delivery.Track:
    description: A music track entity
    properties:
      album:
        type: string
      album_id:
        example: 1
        type: integer
      artists:
        items:
          $ref: '#/definitions/delivery.TrackArtist'
        type: array
      duration:
        example: 216
        type: integer
      id:
        example: 1
        type: integer
      thumbnail_url:
        example: https://example.com/image.jpg
        type: string
      title:
        example: Lagtrain
        type: string
    type: object
  delivery.TrackArtist:
    description: An artist associated with a track
    properties:
      id:
        example: 1
        type: integer
      role:
        example: Main artist
        type: string
      title:
        example: Lagtrain
        type: string
    type: object
  delivery.TrackDetailed:
    properties:
      album:
        type: string
      album_id:
        example: 1
        type: integer
      artists:
        items:
          $ref: '#/definitions/delivery.TrackArtist'
        type: array
      duration:
        example: 216
        type: integer
      file_url:
        example: https://example.com/track.mp3
        type: string
      id:
        example: 1
        type: integer
      thumbnail_url:
        example: https://example.com/image.jpg
        type: string
      title:
        example: Lagtrain
        type: string
    type: object
host: returnzero.ru
info:
  contact: {}
  description: This is the API server for Return Zero music app.
  title: Return Zero API
  version: "1.0"
paths:
  /albums:
    get:
      consumes:
      - application/json
      description: Get a list of albums with optional pagination filters
      parameters:
      - description: 'Offset (default: 0)'
        in: query
        name: offset
        type: integer
      - description: 'Limit (default: 10, max: 100)'
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: List of albums
          schema:
            allOf:
            - $ref: '#/definitions/delivery.APIResponse'
            - properties:
                body:
                  items:
                    $ref: '#/definitions/delivery.Album'
                  type: array
              type: object
        "400":
          description: Bad request - invalid filters
          schema:
            $ref: '#/definitions/delivery.APIBadRequestErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/delivery.APIInternalServerErrorResponse'
      summary: Get albums
      tags:
      - albums
  /artists:
    get:
      consumes:
      - application/json
      description: Get a list of artists with optional pagination filters
      parameters:
      - description: 'Offset (default: 0)'
        in: query
        name: offset
        type: integer
      - description: 'Limit (default: 10, max: 100)'
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: List of artists
          schema:
            allOf:
            - $ref: '#/definitions/delivery.APIResponse'
            - properties:
                body:
                  items:
                    $ref: '#/definitions/delivery.Artist'
                  type: array
              type: object
        "400":
          description: Bad request - invalid filters
          schema:
            $ref: '#/definitions/delivery.APIBadRequestErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/delivery.APIInternalServerErrorResponse'
      summary: Get artists
      tags:
      - artists
  /artists/{id}:
    get:
      consumes:
      - application/json
      description: Get detailed information about a specific artist by their ID
      parameters:
      - description: Artist ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Artist details
          schema:
            allOf:
            - $ref: '#/definitions/delivery.APIResponse'
            - properties:
                body:
                  $ref: '#/definitions/delivery.ArtistDetailed'
              type: object
        "400":
          description: Bad request - invalid ID
          schema:
            $ref: '#/definitions/delivery.APIBadRequestErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/delivery.APIInternalServerErrorResponse'
      summary: Get artist by ID
      tags:
      - artists
  /artists/{id}/albums:
    get:
      consumes:
      - application/json
      description: Get a list of albums for a specific artist
      parameters:
      - description: Artist ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: List of albums
          schema:
            allOf:
            - $ref: '#/definitions/delivery.APIResponse'
            - properties:
                body:
                  items:
                    $ref: '#/definitions/delivery.Album'
                  type: array
              type: object
        "400":
          description: Bad request - invalid artist ID
          schema:
            $ref: '#/definitions/delivery.APIBadRequestErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/delivery.APIInternalServerErrorResponse'
      summary: Get albums by artist ID
      tags:
      - albums
  /artists/{id}/tracks:
    get:
      consumes:
      - application/json
      description: Get a list of tracks by a specific artist with optional pagination
        filters
      parameters:
      - description: Artist ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: List of tracks by artist
          schema:
            allOf:
            - $ref: '#/definitions/delivery.APIResponse'
            - properties:
                body:
                  items:
                    $ref: '#/definitions/delivery.Track'
                  type: array
              type: object
        "400":
          description: Bad request - invalid ID or filters
          schema:
            $ref: '#/definitions/delivery.APIBadRequestErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/delivery.APIInternalServerErrorResponse'
      summary: Get tracks by artist ID
      tags:
      - tracks
  /tracks:
    get:
      consumes:
      - application/json
      description: Get a list of tracks with optional pagination filters
      parameters:
      - description: 'Offset (default: 0)'
        in: query
        name: offset
        type: integer
      - description: 'Limit (default: 10, max: 100)'
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: List of tracks
          schema:
            allOf:
            - $ref: '#/definitions/delivery.APIResponse'
            - properties:
                body:
                  items:
                    $ref: '#/definitions/delivery.Track'
                  type: array
              type: object
        "400":
          description: Bad request - invalid filters
          schema:
            $ref: '#/definitions/delivery.APIBadRequestErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/delivery.APIInternalServerErrorResponse'
      summary: Get tracks
      tags:
      - tracks
  /tracks/{id}:
    get:
      consumes:
      - application/json
      description: Retrieves a specific track by its ID with detailed information
      parameters:
      - description: Track ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Track details
          schema:
            allOf:
            - $ref: '#/definitions/delivery.APIResponse'
            - properties:
                body:
                  $ref: '#/definitions/delivery.TrackDetailed'
              type: object
        "400":
          description: Bad request - invalid ID
          schema:
            $ref: '#/definitions/delivery.APIBadRequestErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/delivery.APIInternalServerErrorResponse'
      summary: Get track by ID
      tags:
      - tracks
swagger: "2.0"
