name: workflow 

on:
  pull_request:
    branches:
      - main
      - dev
      - rk4_cicd

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests and check coverage
        run: |
          make test

      - name: Display coverage percentage
        if: always()
        run: |
          if [ -f coverage_percent.txt ]; then
            COVERAGE=$(cat coverage_percent.txt)
            if [ "${{ job.status }}" = "success" ]; then
              echo "## 🟢 Test Coverage: $COVERAGE" >> $GITHUB_STEP_SUMMARY
            else
              echo "## 🔴 Test Coverage: $COVERAGE" >> $GITHUB_STEP_SUMMARY
            fi
            echo "Coverage percentage: $COVERAGE"
          else
            echo "## 🔴 Coverage percentage file not found" >> $GITHUB_STEP_SUMMARY
            echo "Coverage percentage file not found"
          fi

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: coverage.html
          retention-days: 3

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          args: --timeout=20m --config=./.golangci.yml
          skip-cache: true